"""категории

Revision ID: 9b1817dd83f2
Revises: a3879d254d92
Create Date: 2022-03-05 09:34:40.994470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b1817dd83f2'
down_revision = 'a3879d254d92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
