"""город проживания добавлен

Revision ID: 9e90ecb0d6af
Revises: 
Create Date: 2022-03-04 23:30:31.618202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e90ecb0d6af'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('city_from', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'city_from')
    # ### end Alembic commands ###
